### ISSUE TITLE
Não foi possível "su username"

### ISSUE THREAD

**Issue by bruno-caldas** [Julianobsg/arch-config#1]
Não sei o porquê ainda, mas ao ver o arquivo /etc/passwd no meu usuario tava chamando
/bin/zsh
ao inves de
/bin/bash

**Comment by Julianobsg** [comment]
Pq eu prefiro zsh, a pergunta é, pq o script não instala o zsh..

**Comment by bruno-caldas** [comment]
Ta rapido vc hein...rsrs
Sim, to vendo que ele da um pau na hora install_tools()
Pq nao vem nem o wpa_supplicant nem o tal do zsh

**Comment by bruno-caldas** [comment]
Acho que é porque ele não econtra o display na linha:
"zsh wget htop display wpa_supplicant"

**Comment by Julianobsg** [comment]
retirei o display da instalação, consigo usar o usuário normalmente, no commit https://github.com/Julianobsg/arch-config/commit/e6869ec4248a0b374f656200ce1bf5ce23caae7b
não acontecerá mais esse problema
